export let realtime_weather = {
    location: {
        name: "Noida",
        region: "Uttar Pradesh",
        country: "India",
        lat: 28.57,
        lon: 77.39,
        tz_id: "Asia/Kolkata",
        localtime_epoch: 1641294019,
        localtime: "2022-01-04 16:30",
    },
    current: {
        last_updated_epoch: 1641293100,
        last_updated: "2022-01-04 16:15",
        temp_c: 22,
        temp_f: 71.6,
        is_day: 1,
        condition: {
            text: "Mist",
            icon: "//cdn.weatherapi.com/weather/64x64/day/143.png",
            code: 1030,
        },
        wind_mph: 4.3,
        wind_kph: 6.8,
        wind_degree: 330,
        wind_dir: "NNW",
        pressure_mb: 1016,
        pressure_in: 30,
        precip_mm: 0,
        precip_in: 0,
        humidity: 27,
        cloud: 75,
        feelslike_c: 22.5,
        feelslike_f: 72.6,
        vis_km: 2.5,
        vis_miles: 1,
        uv: 6,
        gust_mph: 3.4,
        gust_kph: 5.4,
        air_quality: {
            co: 2670.300048828125,
            no2: 108.30000305175781,
            o3: 110.19999694824219,
            so2: 133.5,
            pm2_5: 279.29998779296875,
            pm10: 321.6000061035156,
            "us-epa-index": 6,
            "gb-defra-index": 10,
        },
    },
    forecast: {
        forecastday: [
            {
                date: "2022-01-04",
                date_epoch: 1641254400,
                day: {
                    maxtemp_c: 23.5,
                    maxtemp_f: 74.3,
                    mintemp_c: 13.5,
                    mintemp_f: 56.3,
                    avgtemp_c: 18.1,
                    avgtemp_f: 64.7,
                    maxwind_mph: 4.5,
                    maxwind_kph: 7.2,
                    totalprecip_mm: 0,
                    totalprecip_in: 0,
                    avgvis_km: 10,
                    avgvis_miles: 6,
                    avghumidity: 33,
                    daily_will_it_rain: 0,
                    daily_chance_of_rain: 0,
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: 0,
                    condition: {
                        text: "Sunny",
                        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        code: 1000,
                    },
                    uv: 4,
                },
                astro: {
                    sunrise: "07:14 AM",
                    sunset: "05:38 PM",
                    moonrise: "08:47 AM",
                    moonset: "07:24 PM",
                    moon_phase: "Waxing Crescent",
                    moon_illumination: "6",
                },
                hour: [
                    {
                        time_epoch: 1641234600,
                        time: "2022-01-04 00:00",
                        temp_c: 15.2,
                        temp_f: 59.4,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 2.7,
                        wind_kph: 4.3,
                        wind_degree: 284,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 35,
                        cloud: 26,
                        feelslike_c: 15.2,
                        feelslike_f: 59.4,
                        windchill_c: 15.2,
                        windchill_f: 59.4,
                        heatindex_c: 15.2,
                        heatindex_f: 59.4,
                        dewpoint_c: 0,
                        dewpoint_f: 32,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.6,
                        gust_kph: 9,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641238200,
                        time: "2022-01-04 01:00",
                        temp_c: 14.9,
                        temp_f: 58.8,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4,
                        wind_degree: 288,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 33,
                        feelslike_c: 15.6,
                        feelslike_f: 60.1,
                        windchill_c: 15.6,
                        windchill_f: 60.1,
                        heatindex_c: 14.9,
                        heatindex_f: 58.8,
                        dewpoint_c: 0,
                        dewpoint_f: 32,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.1,
                        gust_kph: 8.3,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641241800,
                        time: "2022-01-04 02:00",
                        temp_c: 14.7,
                        temp_f: 58.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 1.8,
                        wind_kph: 2.9,
                        wind_degree: 310,
                        wind_dir: "NW",
                        pressure_mb: 1018,
                        pressure_in: 30.06,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 21,
                        feelslike_c: 14.7,
                        feelslike_f: 58.5,
                        windchill_c: 14.7,
                        windchill_f: 58.5,
                        heatindex_c: 14.7,
                        heatindex_f: 58.5,
                        dewpoint_c: 0,
                        dewpoint_f: 32,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.8,
                        gust_kph: 6.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641245400,
                        time: "2022-01-04 03:00",
                        temp_c: 14.4,
                        temp_f: 57.9,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4,
                        wind_degree: 293,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.05,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 37,
                        cloud: 16,
                        feelslike_c: 15,
                        feelslike_f: 59,
                        windchill_c: 15,
                        windchill_f: 59,
                        heatindex_c: 14.4,
                        heatindex_f: 57.9,
                        dewpoint_c: -0.1,
                        dewpoint_f: 31.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.1,
                        gust_kph: 8.3,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641249000,
                        time: "2022-01-04 04:00",
                        temp_c: 14.1,
                        temp_f: 57.4,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 300,
                        wind_dir: "WNW",
                        pressure_mb: 1017,
                        pressure_in: 30.03,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 9,
                        feelslike_c: 14.5,
                        feelslike_f: 58.1,
                        windchill_c: 14.5,
                        windchill_f: 58.1,
                        heatindex_c: 14.1,
                        heatindex_f: 57.4,
                        dewpoint_c: -0.1,
                        dewpoint_f: 31.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 6,
                        gust_kph: 9.7,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641252600,
                        time: "2022-01-04 05:00",
                        temp_c: 13.9,
                        temp_f: 57,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 1.3,
                        wind_kph: 2.2,
                        wind_degree: 315,
                        wind_dir: "NW",
                        pressure_mb: 1017,
                        pressure_in: 30.03,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 9,
                        feelslike_c: 13.9,
                        feelslike_f: 57,
                        windchill_c: 13.9,
                        windchill_f: 57,
                        heatindex_c: 13.9,
                        heatindex_f: 57,
                        dewpoint_c: -0.1,
                        dewpoint_f: 31.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2.7,
                        gust_kph: 4.3,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641256200,
                        time: "2022-01-04 06:00",
                        temp_c: 13.6,
                        temp_f: 56.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4,
                        wind_degree: 312,
                        wind_dir: "NW",
                        pressure_mb: 1018,
                        pressure_in: 30.05,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 39,
                        cloud: 17,
                        feelslike_c: 14.1,
                        feelslike_f: 57.4,
                        windchill_c: 14.1,
                        windchill_f: 57.4,
                        heatindex_c: 13.6,
                        heatindex_f: 56.5,
                        dewpoint_c: -0.1,
                        dewpoint_f: 31.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.1,
                        gust_kph: 8.3,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641259800,
                        time: "2022-01-04 07:00",
                        temp_c: 13.5,
                        temp_f: 56.3,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 2,
                        wind_kph: 3.2,
                        wind_degree: 302,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 40,
                        cloud: 18,
                        feelslike_c: 14.2,
                        feelslike_f: 57.6,
                        windchill_c: 14.2,
                        windchill_f: 57.6,
                        heatindex_c: 13.5,
                        heatindex_f: 56.3,
                        dewpoint_c: 0.1,
                        dewpoint_f: 32.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 4,
                        gust_kph: 6.5,
                        uv: 4,
                    },
                    {
                        time_epoch: 1641263400,
                        time: "2022-01-04 08:00",
                        temp_c: 14.8,
                        temp_f: 58.6,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 0.9,
                        wind_kph: 1.4,
                        wind_degree: 279,
                        wind_dir: "W",
                        pressure_mb: 1019,
                        pressure_in: 30.08,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 25,
                        feelslike_c: 14.8,
                        feelslike_f: 58.6,
                        windchill_c: 14.8,
                        windchill_f: 58.6,
                        heatindex_c: 14.8,
                        heatindex_f: 58.6,
                        dewpoint_c: 0.7,
                        dewpoint_f: 33.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 1.6,
                        gust_kph: 2.5,
                        uv: 4,
                    },
                    {
                        time_epoch: 1641267000,
                        time: "2022-01-04 09:00",
                        temp_c: 16.7,
                        temp_f: 62.1,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 1.8,
                        wind_kph: 2.9,
                        wind_degree: 273,
                        wind_dir: "W",
                        pressure_mb: 1019,
                        pressure_in: 30.1,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 33,
                        cloud: 22,
                        feelslike_c: 16.7,
                        feelslike_f: 62.1,
                        windchill_c: 16.7,
                        windchill_f: 62.1,
                        heatindex_c: 16.7,
                        heatindex_f: 62.1,
                        dewpoint_c: 0.5,
                        dewpoint_f: 32.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2.5,
                        gust_kph: 4,
                        uv: 5,
                    },
                    {
                        time_epoch: 1641270600,
                        time: "2022-01-04 10:00",
                        temp_c: 18.7,
                        temp_f: 65.7,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 0.9,
                        wind_kph: 1.4,
                        wind_degree: 244,
                        wind_dir: "WSW",
                        pressure_mb: 1019,
                        pressure_in: 30.1,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 30,
                        cloud: 30,
                        feelslike_c: 18.7,
                        feelslike_f: 65.7,
                        windchill_c: 18.7,
                        windchill_f: 65.7,
                        heatindex_c: 18.7,
                        heatindex_f: 65.7,
                        dewpoint_c: 0.7,
                        dewpoint_f: 33.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 1.1,
                        gust_kph: 1.8,
                        uv: 5,
                    },
                    {
                        time_epoch: 1641274200,
                        time: "2022-01-04 11:00",
                        temp_c: 20.9,
                        temp_f: 69.6,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 2,
                        wind_kph: 3.2,
                        wind_degree: 254,
                        wind_dir: "WSW",
                        pressure_mb: 1019,
                        pressure_in: 30.08,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 27,
                        cloud: 22,
                        feelslike_c: 20.9,
                        feelslike_f: 69.6,
                        windchill_c: 20.9,
                        windchill_f: 69.6,
                        heatindex_c: 20.9,
                        heatindex_f: 69.6,
                        dewpoint_c: 1.2,
                        dewpoint_f: 34.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2.2,
                        gust_kph: 3.6,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641277800,
                        time: "2022-01-04 12:00",
                        temp_c: 22,
                        temp_f: 71.6,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 3.1,
                        wind_kph: 5,
                        wind_degree: 286,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.05,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 25,
                        cloud: 25,
                        feelslike_c: 22.7,
                        feelslike_f: 72.9,
                        windchill_c: 22,
                        windchill_f: 71.6,
                        heatindex_c: 22.7,
                        heatindex_f: 72.9,
                        dewpoint_c: 1.1,
                        dewpoint_f: 34,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.6,
                        gust_kph: 5.8,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641281400,
                        time: "2022-01-04 13:00",
                        temp_c: 22.8,
                        temp_f: 73,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 284,
                        wind_dir: "WNW",
                        pressure_mb: 1016,
                        pressure_in: 30.01,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 24,
                        cloud: 32,
                        feelslike_c: 22.9,
                        feelslike_f: 73.2,
                        windchill_c: 22.8,
                        windchill_f: 73,
                        heatindex_c: 22.9,
                        heatindex_f: 73.2,
                        dewpoint_c: 1,
                        dewpoint_f: 33.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.4,
                        gust_kph: 5.4,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641285000,
                        time: "2022-01-04 14:00",
                        temp_c: 23.2,
                        temp_f: 73.8,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4,
                        wind_degree: 287,
                        wind_dir: "WNW",
                        pressure_mb: 1016,
                        pressure_in: 29.99,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 23,
                        cloud: 60,
                        feelslike_c: 23.1,
                        feelslike_f: 73.6,
                        windchill_c: 23.2,
                        windchill_f: 73.8,
                        heatindex_c: 23.1,
                        heatindex_f: 73.6,
                        dewpoint_c: 1,
                        dewpoint_f: 33.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2.9,
                        gust_kph: 4.7,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641288600,
                        time: "2022-01-04 15:00",
                        temp_c: 23.3,
                        temp_f: 73.9,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 305,
                        wind_dir: "NW",
                        pressure_mb: 1015,
                        pressure_in: 29.98,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 23,
                        cloud: 33,
                        feelslike_c: 23.2,
                        feelslike_f: 73.8,
                        windchill_c: 23.3,
                        windchill_f: 73.9,
                        heatindex_c: 23.2,
                        heatindex_f: 73.8,
                        dewpoint_c: 1.3,
                        dewpoint_f: 34.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.4,
                        gust_kph: 5.4,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641292200,
                        time: "2022-01-04 16:00",
                        temp_c: 23.5,
                        temp_f: 74.3,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.7,
                        wind_kph: 4.3,
                        wind_degree: 3,
                        wind_dir: "N",
                        pressure_mb: 1015,
                        pressure_in: 29.97,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 26,
                        cloud: 11,
                        feelslike_c: 23.6,
                        feelslike_f: 74.5,
                        windchill_c: 23.5,
                        windchill_f: 74.3,
                        heatindex_c: 23.6,
                        heatindex_f: 74.5,
                        dewpoint_c: 3.1,
                        dewpoint_f: 37.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.1,
                        gust_kph: 5,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641295800,
                        time: "2022-01-04 17:00",
                        temp_c: 21.7,
                        temp_f: 71.1,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 53,
                        wind_dir: "NE",
                        pressure_mb: 1015,
                        pressure_in: 29.97,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 28,
                        cloud: 15,
                        feelslike_c: 21.7,
                        feelslike_f: 71.1,
                        windchill_c: 21.7,
                        windchill_f: 71.1,
                        heatindex_c: 23,
                        heatindex_f: 73.4,
                        dewpoint_c: 2.5,
                        dewpoint_f: 36.5,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 6.3,
                        gust_kph: 10.1,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641299400,
                        time: "2022-01-04 18:00",
                        temp_c: 20.5,
                        temp_f: 68.9,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.9,
                        wind_kph: 4.7,
                        wind_degree: 62,
                        wind_dir: "ENE",
                        pressure_mb: 1016,
                        pressure_in: 29.99,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 31,
                        cloud: 23,
                        feelslike_c: 20.5,
                        feelslike_f: 68.9,
                        windchill_c: 20.5,
                        windchill_f: 68.9,
                        heatindex_c: 20.5,
                        heatindex_f: 68.9,
                        dewpoint_c: 2.8,
                        dewpoint_f: 37,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 4.5,
                        gust_kph: 7.2,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641303000,
                        time: "2022-01-04 19:00",
                        temp_c: 20.3,
                        temp_f: 68.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.7,
                        wind_kph: 4.3,
                        wind_degree: 87,
                        wind_dir: "E",
                        pressure_mb: 1016,
                        pressure_in: 30,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 33,
                        cloud: 17,
                        feelslike_c: 20.3,
                        feelslike_f: 68.5,
                        windchill_c: 20.3,
                        windchill_f: 68.5,
                        heatindex_c: 20.3,
                        heatindex_f: 68.5,
                        dewpoint_c: 3.5,
                        dewpoint_f: 38.3,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 4,
                        gust_kph: 6.5,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641306600,
                        time: "2022-01-04 20:00",
                        temp_c: 18.5,
                        temp_f: 65.3,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 1.3,
                        wind_kph: 2.2,
                        wind_degree: 79,
                        wind_dir: "E",
                        pressure_mb: 1017,
                        pressure_in: 30.03,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 35,
                        cloud: 20,
                        feelslike_c: 18.5,
                        feelslike_f: 65.3,
                        windchill_c: 18.5,
                        windchill_f: 65.3,
                        heatindex_c: 18.5,
                        heatindex_f: 65.3,
                        dewpoint_c: 2.8,
                        dewpoint_f: 37,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2.5,
                        gust_kph: 4,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641310200,
                        time: "2022-01-04 21:00",
                        temp_c: 18.2,
                        temp_f: 64.8,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 1.1,
                        wind_kph: 1.8,
                        wind_degree: 178,
                        wind_dir: "S",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 17,
                        feelslike_c: 18.2,
                        feelslike_f: 64.8,
                        windchill_c: 18.2,
                        windchill_f: 64.8,
                        heatindex_c: 18.2,
                        heatindex_f: 64.8,
                        dewpoint_c: 2.7,
                        dewpoint_f: 36.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 2,
                        gust_kph: 3.2,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641313800,
                        time: "2022-01-04 22:00",
                        temp_c: 18.3,
                        temp_f: 64.9,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 2.5,
                        wind_kph: 4,
                        wind_degree: 139,
                        wind_dir: "SE",
                        pressure_mb: 1018,
                        pressure_in: 30.06,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 14,
                        feelslike_c: 18.3,
                        feelslike_f: 64.9,
                        windchill_c: 18.3,
                        windchill_f: 64.9,
                        heatindex_c: 18.3,
                        heatindex_f: 64.9,
                        dewpoint_c: 2.8,
                        dewpoint_f: 37,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 4.5,
                        gust_kph: 7.2,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641317400,
                        time: "2022-01-04 23:00",
                        temp_c: 17.7,
                        temp_f: 63.9,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4,
                        wind_kph: 6.5,
                        wind_degree: 131,
                        wind_dir: "SE",
                        pressure_mb: 1017,
                        pressure_in: 30.04,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 37,
                        cloud: 16,
                        feelslike_c: 17.7,
                        feelslike_f: 63.9,
                        windchill_c: 17.7,
                        windchill_f: 63.9,
                        heatindex_c: 17.7,
                        heatindex_f: 63.9,
                        dewpoint_c: 2.9,
                        dewpoint_f: 37.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 7.6,
                        gust_kph: 12.2,
                        uv: 1,
                    },
                ],
            },
        ],
    },
};

export let moonphases_url = {
    fullmoon:
        "https://ik.imagekit.io/dchud9yflpr/fullmoon_hSKsqGBY9.svg?updatedAt=1641305305496",
    fullmoontransparent:
        "https://ik.imagekit.io/dchud9yflpr/fullmoontransparent_OXo6IATtL0F.svg?updatedAt=1641306098218",
    firstquarter:
        "https://ik.imagekit.io/dchud9yflpr/firstquarter_1__alRmNeSn4N_q.svg?updatedAt=1641305905172",
    firstquartertransparent:
        "https://ik.imagekit.io/dchud9yflpr/firstquarter_transparent_7SQv5hRVk.svg?updatedAt=1641305786254",
    lastquarter:
        "https://ik.imagekit.io/dchud9yflpr/lastquarter_8-pvMNFZR.svg?updatedAt=1641306566665",
    lastquartertransparent:
        "https://ik.imagekit.io/dchud9yflpr/lastquartertransparent_FEqkCvDL3.svg?updatedAt=1641306566793",
    waxingcrescent:
        "https://ik.imagekit.io/dchud9yflpr/waxingcrescent_ccOU9Hwn9c1.svg?updatedAt=1641306189861",
    waxingcrescenttransparent:
        "https://ik.imagekit.io/dchud9yflpr/waxingcrescenttransparent_KC2n2u7tP.svg?updatedAt=1641306123167",
    waningcrescent:
        "https://ik.imagekit.io/dchud9yflpr/waningcrescent_ABUuDzzFT.svg?updatedAt=1641306478952",
    waningcrescenttransparent:
        "https://ik.imagekit.io/dchud9yflpr/waningcrescenttransparent_0xW6ExPsG.svg?updatedAt=1641306478965",
};

export let activemoonphases = new Map([
    [
        "Full Moon",
        "https://ik.imagekit.io/dchud9yflpr/fullmoon_hSKsqGBY9.svg?updatedAt=1641305305496",
    ],
    [
        "Waxing Crescent",
        "https://ik.imagekit.io/dchud9yflpr/waxingcrescent_ccOU9Hwn9c1.svg?updatedAt=1641306189861",
    ],
    [
        "First Quarter",
        "https://ik.imagekit.io/dchud9yflpr/firstquarter_1__alRmNeSn4N_q.svg?updatedAt=1641305905172",
    ],
    [
        "Waxing Gibbous",
        "https://ik.imagekit.io/dchud9yflpr/fullmoon_hSKsqGBY9.svg?updatedAt=1641305305496",
    ],
    [
        "Last Quarter",
        "https://ik.imagekit.io/dchud9yflpr/lastquarter_8-pvMNFZR.svg?updatedAt=1641306566665",
    ],
    [
        "Waning Gibbous",
        "https://ik.imagekit.io/dchud9yflpr/fullmoon_hSKsqGBY9.svg?updatedAt=1641305305496",
    ],
    [
        "Waning Crescent",
        "https://ik.imagekit.io/dchud9yflpr/waningcrescent_ABUuDzzFT.svg?updatedAt=1641306478952",
    ],
]);

export let inactivemoonphases = new Map([
    [
        "Full Moon",
        "https://ik.imagekit.io/dchud9yflpr/fullmoontransparent_OXo6IATtL0F.svg?updatedAt=1641306098218",
    ],
    [
        "Waxing Crescent",
        "https://ik.imagekit.io/dchud9yflpr/waxingcrescenttransparent_KC2n2u7tP.svg?updatedAt=1641306123167",
    ],
    [
        "First Quarter",
        "https://ik.imagekit.io/dchud9yflpr/firstquarter_transparent_7SQv5hRVk.svg?updatedAt=1641305786254",
    ],
    [
        "Waxing Gibbous",
        "https://ik.imagekit.io/dchud9yflpr/fullmoontransparent_OXo6IATtL0F.svg?updatedAt=1641306098218",
    ],
    [
        "Last Quarter",
        "https://ik.imagekit.io/dchud9yflpr/lastquartertransparent_FEqkCvDL3.svg?updatedAt=1641306566793",
    ],
    [
        "Waning Gibbous",
        "https://ik.imagekit.io/dchud9yflpr/fullmoontransparent_OXo6IATtL0F.svg?updatedAt=1641306098218",
    ],
    [
        "Waning Crescent",
        "https://ik.imagekit.io/dchud9yflpr/waningcrescenttransparent_0xW6ExPsG.svg?updatedAt=1641306478965",
    ],
]);
// export let realtime_weather;
// let lat, long;
// window.navigator.geolocation.getCurrentPosition(
//     function (location) {
//         lat = location.coords.latitude;
//         long = location.coords.longitude;
//         fetch(
//             `https://api.weatherapi.com/v1/current.json?key=07ea304d0187480f863192418220201&q=${lat},${long}&aqi=yes`
//         )
//             .then((response) => response.json())
//             .then(function (data) {
//                 realtime_weather = data;
//             });
//     },
//     (err) => {
//         console.log(err);
//     },
//     { enableHighAccuracy: true }
// );
