export let realtime_weather = {
    location: {
        name: "Merath",
        region: "Uttar Pradesh",
        country: "India",
        lat: 29.02,
        lon: 77.77,
        tz_id: "Asia/Kolkata",
        localtime_epoch: 1641226525,
        localtime: "2022-01-03 21:45",
    },
    current: {
        last_updated_epoch: 1641226500,
        last_updated: "2022-01-03 21:45",
        temp_c: 14.7,
        temp_f: 58.5,
        is_day: 0,
        condition: {
            text: "Partly cloudy",
            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
            code: 1003,
        },
        wind_mph: 4.5,
        wind_kph: 7.2,
        wind_degree: 300,
        wind_dir: "WNW",
        pressure_mb: 1018,
        pressure_in: 30.05,
        precip_mm: 0,
        precip_in: 0,
        humidity: 46,
        cloud: 32,
        feelslike_c: 14.7,
        feelslike_f: 58.5,
        vis_km: 10,
        vis_miles: 6,
        uv: 1,
        gust_mph: 9.4,
        gust_kph: 15.1,
        air_quality: {
            co: 1522.0999755859375,
            no2: 22.299999237060547,
            o3: 91.5999984741211,
            so2: 11.899999618530273,
            pm2_5: 239.39999389648438,
            pm10: 270.70001220703125,
            "us-epa-index": 5,
            "gb-defra-index": 10,
        },
    },
    forecast: {
        forecastday: [
            {
                date: "2022-01-03",
                date_epoch: 1641168000,
                day: {
                    maxtemp_c: 21.5,
                    maxtemp_f: 70.7,
                    mintemp_c: 9.7,
                    mintemp_f: 49.5,
                    avgtemp_c: 14.9,
                    avgtemp_f: 58.8,
                    maxwind_mph: 7.2,
                    maxwind_kph: 11.5,
                    totalprecip_mm: 0,
                    totalprecip_in: 0,
                    avgvis_km: 10,
                    avgvis_miles: 6,
                    avghumidity: 36,
                    daily_will_it_rain: 0,
                    daily_chance_of_rain: 0,
                    daily_will_it_snow: 0,
                    daily_chance_of_snow: 0,
                    condition: {
                        text: "Sunny",
                        icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                        code: 1000,
                    },
                    uv: 4,
                },
                astro: {
                    sunrise: "07:13 AM",
                    sunset: "05:34 PM",
                    moonrise: "07:49 AM",
                    moonset: "06:10 PM",
                    moon_phase: "New Moon",
                    moon_illumination: "0",
                },
                hour: [
                    {
                        time_epoch: 1641148200,
                        time: "2022-01-03 00:00",
                        temp_c: 11.8,
                        temp_f: 53.2,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 309,
                        wind_dir: "NW",
                        pressure_mb: 1019,
                        pressure_in: 30.1,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 4,
                        feelslike_c: 11.3,
                        feelslike_f: 52.3,
                        windchill_c: 11.3,
                        windchill_f: 52.3,
                        heatindex_c: 11.8,
                        heatindex_f: 53.2,
                        dewpoint_c: -2,
                        dewpoint_f: 28.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641151800,
                        time: "2022-01-03 01:00",
                        temp_c: 11.4,
                        temp_f: 52.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 310,
                        wind_dir: "NW",
                        pressure_mb: 1019,
                        pressure_in: 30.09,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 3,
                        feelslike_c: 10.8,
                        feelslike_f: 51.4,
                        windchill_c: 10.8,
                        windchill_f: 51.4,
                        heatindex_c: 11.4,
                        heatindex_f: 52.5,
                        dewpoint_c: -2.4,
                        dewpoint_f: 27.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641155400,
                        time: "2022-01-03 02:00",
                        temp_c: 10.6,
                        temp_f: 51.1,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4,
                        wind_kph: 6.5,
                        wind_degree: 323,
                        wind_dir: "NW",
                        pressure_mb: 1019,
                        pressure_in: 30.09,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 38,
                        cloud: 2,
                        feelslike_c: 10,
                        feelslike_f: 50,
                        windchill_c: 10,
                        windchill_f: 50,
                        heatindex_c: 10.6,
                        heatindex_f: 51.1,
                        dewpoint_c: -3.1,
                        dewpoint_f: 26.4,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641159000,
                        time: "2022-01-03 03:00",
                        temp_c: 10.5,
                        temp_f: 50.9,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 3.8,
                        wind_kph: 6.1,
                        wind_degree: 313,
                        wind_dir: "NW",
                        pressure_mb: 1019,
                        pressure_in: 30.08,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 37,
                        cloud: 3,
                        feelslike_c: 10,
                        feelslike_f: 50,
                        windchill_c: 10,
                        windchill_f: 50,
                        heatindex_c: 10.5,
                        heatindex_f: 50.9,
                        dewpoint_c: -3.5,
                        dewpoint_f: 25.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.1,
                        gust_kph: 13,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641162600,
                        time: "2022-01-03 04:00",
                        temp_c: 10.4,
                        temp_f: 50.7,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 299,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 3,
                        feelslike_c: 9.7,
                        feelslike_f: 49.5,
                        windchill_c: 9.7,
                        windchill_f: 49.5,
                        heatindex_c: 10.4,
                        heatindex_f: 50.7,
                        dewpoint_c: -3.9,
                        dewpoint_f: 25,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641166200,
                        time: "2022-01-03 05:00",
                        temp_c: 10,
                        temp_f: 50,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4,
                        wind_kph: 6.5,
                        wind_degree: 306,
                        wind_dir: "NW",
                        pressure_mb: 1018,
                        pressure_in: 30.07,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 36,
                        cloud: 21,
                        feelslike_c: 9.3,
                        feelslike_f: 48.7,
                        windchill_c: 9.3,
                        windchill_f: 48.7,
                        heatindex_c: 10,
                        heatindex_f: 50,
                        dewpoint_c: -4.5,
                        dewpoint_f: 23.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641169800,
                        time: "2022-01-03 06:00",
                        temp_c: 9.7,
                        temp_f: 49.5,
                        is_day: 0,
                        condition: {
                            text: "Clear",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                            code: 1000,
                        },
                        wind_mph: 4.3,
                        wind_kph: 6.8,
                        wind_degree: 300,
                        wind_dir: "WNW",
                        pressure_mb: 1019,
                        pressure_in: 30.09,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 35,
                        cloud: 12,
                        feelslike_c: 8.9,
                        feelslike_f: 48,
                        windchill_c: 8.9,
                        windchill_f: 48,
                        heatindex_c: 9.7,
                        heatindex_f: 49.5,
                        dewpoint_c: -5,
                        dewpoint_f: 23,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.9,
                        gust_kph: 14.4,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641173400,
                        time: "2022-01-03 07:00",
                        temp_c: 9.7,
                        temp_f: 49.5,
                        is_day: 1,
                        condition: {
                            text: "Overcast",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/122.png",
                            code: 1009,
                        },
                        wind_mph: 4,
                        wind_kph: 6.5,
                        wind_degree: 299,
                        wind_dir: "WNW",
                        pressure_mb: 1019,
                        pressure_in: 30.09,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 34,
                        cloud: 89,
                        feelslike_c: 9,
                        feelslike_f: 48.2,
                        windchill_c: 9,
                        windchill_f: 48.2,
                        heatindex_c: 9.7,
                        heatindex_f: 49.5,
                        dewpoint_c: -5.2,
                        dewpoint_f: 22.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 2,
                    },
                    {
                        time_epoch: 1641177000,
                        time: "2022-01-03 08:00",
                        temp_c: 11.6,
                        temp_f: 52.9,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 3.6,
                        wind_kph: 5.8,
                        wind_degree: 329,
                        wind_dir: "NNW",
                        pressure_mb: 1020,
                        pressure_in: 30.13,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 33,
                        cloud: 62,
                        feelslike_c: 11.4,
                        feelslike_f: 52.5,
                        windchill_c: 11.4,
                        windchill_f: 52.5,
                        heatindex_c: 11.6,
                        heatindex_f: 52.9,
                        dewpoint_c: -4,
                        dewpoint_f: 24.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 6.3,
                        gust_kph: 10.1,
                        uv: 4,
                    },
                    {
                        time_epoch: 1641180600,
                        time: "2022-01-03 09:00",
                        temp_c: 14.1,
                        temp_f: 57.4,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 4,
                        wind_kph: 6.5,
                        wind_degree: 300,
                        wind_dir: "WNW",
                        pressure_mb: 1021,
                        pressure_in: 30.14,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 29,
                        cloud: 36,
                        feelslike_c: 14.1,
                        feelslike_f: 57.4,
                        windchill_c: 14.1,
                        windchill_f: 57.4,
                        heatindex_c: 14.1,
                        heatindex_f: 57.4,
                        dewpoint_c: -3.8,
                        dewpoint_f: 25.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.4,
                        gust_kph: 8.6,
                        uv: 4,
                    },
                    {
                        time_epoch: 1641184200,
                        time: "2022-01-03 10:00",
                        temp_c: 16.5,
                        temp_f: 61.7,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 3.1,
                        wind_kph: 5,
                        wind_degree: 328,
                        wind_dir: "NNW",
                        pressure_mb: 1020,
                        pressure_in: 30.12,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 26,
                        cloud: 6,
                        feelslike_c: 16.5,
                        feelslike_f: 61.7,
                        windchill_c: 16.5,
                        windchill_f: 61.7,
                        heatindex_c: 16.5,
                        heatindex_f: 61.7,
                        dewpoint_c: -3.3,
                        dewpoint_f: 26.1,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 3.6,
                        gust_kph: 5.8,
                        uv: 5,
                    },
                    {
                        time_epoch: 1641187800,
                        time: "2022-01-03 11:00",
                        temp_c: 18.6,
                        temp_f: 65.5,
                        is_day: 1,
                        condition: {
                            text: "Cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/119.png",
                            code: 1006,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 306,
                        wind_dir: "NW",
                        pressure_mb: 1019,
                        pressure_in: 30.1,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 24,
                        cloud: 64,
                        feelslike_c: 18.6,
                        feelslike_f: 65.5,
                        windchill_c: 18.6,
                        windchill_f: 65.5,
                        heatindex_c: 18.6,
                        heatindex_f: 65.5,
                        dewpoint_c: -2.4,
                        dewpoint_f: 27.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 5.4,
                        gust_kph: 8.6,
                        uv: 4,
                    },
                    {
                        time_epoch: 1641191400,
                        time: "2022-01-03 12:00",
                        temp_c: 20.5,
                        temp_f: 68.9,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 5.6,
                        wind_kph: 9,
                        wind_degree: 294,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.05,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 24,
                        cloud: 3,
                        feelslike_c: 20.5,
                        feelslike_f: 68.9,
                        windchill_c: 20.5,
                        windchill_f: 68.9,
                        heatindex_c: 20.5,
                        heatindex_f: 68.9,
                        dewpoint_c: -0.8,
                        dewpoint_f: 30.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 6.5,
                        gust_kph: 10.4,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641195000,
                        time: "2022-01-03 13:00",
                        temp_c: 21.4,
                        temp_f: 70.5,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 6.3,
                        wind_kph: 10.1,
                        wind_degree: 288,
                        wind_dir: "WNW",
                        pressure_mb: 1017,
                        pressure_in: 30.02,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 25,
                        cloud: 6,
                        feelslike_c: 21.4,
                        feelslike_f: 70.5,
                        windchill_c: 21.4,
                        windchill_f: 70.5,
                        heatindex_c: 22.4,
                        heatindex_f: 72.3,
                        dewpoint_c: 0.4,
                        dewpoint_f: 32.7,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 7.2,
                        gust_kph: 11.5,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641198600,
                        time: "2022-01-03 14:00",
                        temp_c: 21.5,
                        temp_f: 70.7,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 7.2,
                        wind_kph: 11.5,
                        wind_degree: 284,
                        wind_dir: "WNW",
                        pressure_mb: 1016,
                        pressure_in: 30,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 27,
                        cloud: 12,
                        feelslike_c: 21.5,
                        feelslike_f: 70.7,
                        windchill_c: 21.5,
                        windchill_f: 70.7,
                        heatindex_c: 22.8,
                        heatindex_f: 73,
                        dewpoint_c: 1.7,
                        dewpoint_f: 35.1,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.3,
                        gust_kph: 13.3,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641202200,
                        time: "2022-01-03 15:00",
                        temp_c: 21.5,
                        temp_f: 70.7,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 7.2,
                        wind_kph: 11.5,
                        wind_degree: 288,
                        wind_dir: "WNW",
                        pressure_mb: 1016,
                        pressure_in: 29.99,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 28,
                        cloud: 15,
                        feelslike_c: 21.5,
                        feelslike_f: 70.7,
                        windchill_c: 21.5,
                        windchill_f: 70.7,
                        heatindex_c: 22.9,
                        heatindex_f: 73.2,
                        dewpoint_c: 2.5,
                        dewpoint_f: 36.5,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.5,
                        gust_kph: 13.7,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641205800,
                        time: "2022-01-03 16:00",
                        temp_c: 20.5,
                        temp_f: 68.9,
                        is_day: 1,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
                            code: 1003,
                        },
                        wind_mph: 6,
                        wind_kph: 9.7,
                        wind_degree: 282,
                        wind_dir: "WNW",
                        pressure_mb: 1016,
                        pressure_in: 29.99,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 35,
                        cloud: 25,
                        feelslike_c: 20.5,
                        feelslike_f: 68.9,
                        windchill_c: 20.5,
                        windchill_f: 68.9,
                        heatindex_c: 20.5,
                        heatindex_f: 68.9,
                        dewpoint_c: 4.5,
                        dewpoint_f: 40.1,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.7,
                        gust_kph: 14,
                        uv: 6,
                    },
                    {
                        time_epoch: 1641209400,
                        time: "2022-01-03 17:00",
                        temp_c: 17.6,
                        temp_f: 63.7,
                        is_day: 1,
                        condition: {
                            text: "Sunny",
                            icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                            code: 1000,
                        },
                        wind_mph: 6,
                        wind_kph: 9.7,
                        wind_degree: 275,
                        wind_dir: "W",
                        pressure_mb: 1016,
                        pressure_in: 30,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 40,
                        cloud: 23,
                        feelslike_c: 17.6,
                        feelslike_f: 63.7,
                        windchill_c: 17.6,
                        windchill_f: 63.7,
                        heatindex_c: 17.6,
                        heatindex_f: 63.7,
                        dewpoint_c: 3.9,
                        dewpoint_f: 39,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 12.3,
                        gust_kph: 19.8,
                        uv: 5,
                    },
                    {
                        time_epoch: 1641213000,
                        time: "2022-01-03 18:00",
                        temp_c: 16.4,
                        temp_f: 61.5,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 5.8,
                        wind_kph: 9.4,
                        wind_degree: 284,
                        wind_dir: "WNW",
                        pressure_mb: 1017,
                        pressure_in: 30.03,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 43,
                        cloud: 26,
                        feelslike_c: 16.4,
                        feelslike_f: 61.5,
                        windchill_c: 16.4,
                        windchill_f: 61.5,
                        heatindex_c: 16.4,
                        heatindex_f: 61.5,
                        dewpoint_c: 3.8,
                        dewpoint_f: 38.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 12.3,
                        gust_kph: 19.8,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641216600,
                        time: "2022-01-03 19:00",
                        temp_c: 15.7,
                        temp_f: 60.3,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 292,
                        wind_dir: "WNW",
                        pressure_mb: 1017,
                        pressure_in: 30.04,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 45,
                        cloud: 33,
                        feelslike_c: 15.7,
                        feelslike_f: 60.3,
                        windchill_c: 15.7,
                        windchill_f: 60.3,
                        heatindex_c: 15.7,
                        heatindex_f: 60.3,
                        dewpoint_c: 3.8,
                        dewpoint_f: 38.8,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.8,
                        gust_kph: 15.8,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641220200,
                        time: "2022-01-03 20:00",
                        temp_c: 14.7,
                        temp_f: 58.5,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 300,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.05,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 46,
                        cloud: 32,
                        feelslike_c: 14.7,
                        feelslike_f: 58.5,
                        windchill_c: 14.7,
                        windchill_f: 58.5,
                        heatindex_c: 14.7,
                        heatindex_f: 58.5,
                        dewpoint_c: 3.3,
                        dewpoint_f: 37.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641223800,
                        time: "2022-01-03 21:00",
                        temp_c: 14.4,
                        temp_f: 57.9,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.5,
                        wind_kph: 7.2,
                        wind_degree: 287,
                        wind_dir: "WNW",
                        pressure_mb: 1018,
                        pressure_in: 30.06,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 46,
                        cloud: 31,
                        feelslike_c: 14.3,
                        feelslike_f: 57.7,
                        windchill_c: 14.3,
                        windchill_f: 57.7,
                        heatindex_c: 14.4,
                        heatindex_f: 57.9,
                        dewpoint_c: 3.1,
                        dewpoint_f: 37.6,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.4,
                        gust_kph: 15.1,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641227400,
                        time: "2022-01-03 22:00",
                        temp_c: 14.1,
                        temp_f: 57.4,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.7,
                        wind_kph: 7.6,
                        wind_degree: 285,
                        wind_dir: "WNW",
                        pressure_mb: 1019,
                        pressure_in: 30.08,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 47,
                        cloud: 25,
                        feelslike_c: 13.9,
                        feelslike_f: 57,
                        windchill_c: 13.9,
                        windchill_f: 57,
                        heatindex_c: 14.1,
                        heatindex_f: 57.4,
                        dewpoint_c: 2.9,
                        dewpoint_f: 37.2,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 9.8,
                        gust_kph: 15.8,
                        uv: 1,
                    },
                    {
                        time_epoch: 1641231000,
                        time: "2022-01-03 23:00",
                        temp_c: 13.7,
                        temp_f: 56.7,
                        is_day: 0,
                        condition: {
                            text: "Partly cloudy",
                            icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                            code: 1003,
                        },
                        wind_mph: 4.3,
                        wind_kph: 6.8,
                        wind_degree: 299,
                        wind_dir: "WNW",
                        pressure_mb: 1019,
                        pressure_in: 30.08,
                        precip_mm: 0,
                        precip_in: 0,
                        humidity: 47,
                        cloud: 26,
                        feelslike_c: 13.6,
                        feelslike_f: 56.5,
                        windchill_c: 13.6,
                        windchill_f: 56.5,
                        heatindex_c: 13.7,
                        heatindex_f: 56.7,
                        dewpoint_c: 2.7,
                        dewpoint_f: 36.9,
                        will_it_rain: 0,
                        chance_of_rain: 0,
                        will_it_snow: 0,
                        chance_of_snow: 0,
                        vis_km: 10,
                        vis_miles: 6,
                        gust_mph: 8.9,
                        gust_kph: 14.4,
                        uv: 1,
                    },
                ],
            },
        ],
    },
};

// let lat, long;
// window.navigator.geolocation.getCurrentPosition(
//     function (location) {
//         lat = location.coords.latitude;
//         long = location.coords.longitude;
//         fetch(
//             `https://api.weatherapi.com/v1/current.json?key=07ea304d0187480f863192418220201&q=${lat},${long}&aqi=yes`
//         )
//             .then((response) => response.json())
//             .then(console.log);
//     },
//     (err) => {
//         console.log(err);
//     },
//     { enableHighAccuracy: true }
// );
